### ISSUE TITLE
Variable arguments causes String.format to break

### ISSUE THREAD

**Issue by JasonWaataja** [t-rasmud/checker-framework#10]
The `String.format` method uses a variable length argument list, which isn't handled correctly. This means that the format method requires a `@Det` argument sometimes when it should only require `@PolyDet`.

An simple example would be:
```java
public class FormatExample {
    public static String itoa(int value) {
        return String.format("%s", value);
    }
}
```
which gives the error:
```
javac -processor DeterminismChecker FormatExample.java
FormatExample.java:3: error: [argument.type.incompatible] incompatible types in argument.
        return String.format("%s", value);
                                   ^
  found   : @PolyDet int
  required: @Det Object
1 error
```

I believe this argument should return a `@PolyDet` value and accept a `@PolyDet` value.

**Comment by t-rasmud** [comment]
The parameter in `public static String itoa(int value)` is annotated as `@Det int @PolyDet[] value` by default. Since the components of the array have type `@Det`,  the argument to `format (value)` has type `@Det` resulting in this error. 
I have changed the default type of all array parameters to be `@PolyDet type @PolyDet[]` in [bafb7d4edffb19c3959a51f3e68ab871ea7e9afc]()
